
# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

# we are not building Visual Studio project, so default build step is off
build: off

environment:
  matrix:
    - platform: x86
      PYTHON: "C:\\Python27"

    - platform: x64
      PYTHON: "C:\\Python27-x64"

    - platform: x86
      PYTHON: "C:\\Python35"

    - platform: x64
      PYTHON: "C:\\Python35-x64"

    - platform: x86
      PYTHON: "C:\\Python36"

    - platform: x64
      PYTHON: "C:\\Python36-x64"


init:
# add Python interpreter to PATH variable
  - set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
# following this one: https://github.com/audreyr/cookiecutter/issues/599
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
# check python version
  - python -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"


install:
# check pip version and upgrade it
  - python -m pip -V
  - pip install --upgrade pip --user
  - python -m pip -V
# install usual requirements
  - python -m pip install --upgrade -r tests/requirements-test.txt
  - python -m pip install --upgrade -r requirements.txt
# check numpy version
  - python -c "import numpy as np;print(np.version.version)"
# check python and pip versions
  - python -V
  - python -m pip -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"

before_test:
  - python %PYTHON%\\scripts\\versioneer install

test_script:
# make wheel package
  - python -m pip install wheel
  - python setup.py bdist_wheel
# clean build directory
  - rd /s /q build
# install generated package
  - python -m pip install --ignore-installed --force-reinstall --no-index --find-links=dist pymchelper
# install optional deps
  - python -m pip install matplotlib
# pytrip98 installation (optional)
  - python -m pip install pytrip98
# run tests (normal py.test command may results in memory error on appveyor, so we run tests file-by-file)
  - del tests\\test_default_converter.py # remove one of the problematic tests
  - ps: Get-ChildItem -Path tests\ -Recurse -Include test*.py | foreach-object { $(echo $_ | Out-Host ; python -m pytest $_ | Out-Host; $?) -or $(break)}


