
# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

# we are not building Visual Studio project, so default build step is off
build: off

environment:
  matrix:
    - platform: x86
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      MINICONDAPATH: "C:\\Miniconda"

    - platform: x64
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      MINICONDAPATH: "C:\\Miniconda"

    - platform: x86
      PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      MINICONDAPATH: "C:\\Miniconda3"

    - platform: x64
      PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      MINICONDAPATH: "C:\\Miniconda3-x64"

    - platform: x86
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      MINICONDAPATH: "C:\\Miniconda35"

    - platform: x64
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      MINICONDAPATH: "C:\\Miniconda35-x64"


init:
# add Python interpreter to PATH variable
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
# add Miniconda to PATH variable
  - set PATH=%MINICONDAPATH%\Scripts;%PATH%
# following this one: https://github.com/audreyr/cookiecutter/issues/599
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
# check python version
  - python -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"


install:
# tell miniconda to always follow default answers
  - conda config --set always_yes yes --set changeps1 no
# update miniconda
  - conda update -q conda
# create new conda workspace and activate it
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
# check pip version and upgrade it
  - pip -V
  - pip install --upgrade pip
# install usual requirements
  - pip install --upgrade -r tests/requirements-test.txt
  - pip install --upgrade -r requirements.txt
# check numpy version
  - python -c "import numpy as np;print(np.version.version)"
# check python and pip versions
  - python -V
  - pip -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"

before_test:
  - python %MINICONDAPATH%\envs\python%PYTHON_VERSION%\scripts\versioneer install

test_script:
# make wheel package
  - python setup.py bdist_wheel
# clean build directory
  - rd /s /q build
# install generated package
  - cd dist
  - python -c "import os; import pip; pip.main(['install', os.listdir('.')[0]]);"
  - cd ..
# install optional deps
  - pip install matplotlib
# pytrip98 is available only for Python 3.5, lets install it together with deps
  - ps: If ($env:PYTHON_VERSION -eq "3.5") {conda install -q --name python%PYTHON_VERSION% scipy}
  - ps: If ($env:PYTHON_VERSION -eq "3.5") {python -c "import scipy as sp;print(sp.version.version)"}
  - ps: If ($env:PYTHON_VERSION -eq "3.5") {pip install pytrip98}
# run tests (normal py.test command results in memory error on appveyor, so we run tests file-by-file)
  - FOR %%I in (tests\test*.py) DO python -m pytest %%I
